export const LINE_THROUGH = 'LINE_THROUGH';
export const LINE_THROUGH_2 = 'LINE_THROUGH_2';
export const UNMOUNT_SUCCESS = 'UNMOUNT_SUCCESS';
export const MOUNT_SUCCESS = 'MOUNT_SUCCESS';
export const SAVE_WEEK = 'SAVE_WEEK';
export const SAVE_TIMENOW = 'SAVE_TIMENOW';
export const SAVE_HISTORY = 'SAVE_HISTORY';
export const SAVE_WEEKNOW = 'SAVE_WEEKNOW';